#!/usr/bin/env python3
"""Dump a deck's speaker notes to markdown, so they can be read and reviewed in git.

    python export-notes.py finops-gaining-visibility-cfo.pptx speaker-notes-cfo.md

Requires python-pptx. Notes are authored in notes-*.js and baked into the deck by
build-deck.js — regenerate the deck first, then re-run this.
"""
import sys

from pptx import Presentation

INTRO = """# Speaker notes — {label}

Notes as they appear in `{deck}`, reproduced here so they can be read and
reviewed without opening PowerPoint.

Generated by `export-notes.py`. To change a note, edit the matching entry in
`notes-*.js`, rebuild the deck, and re-run the export — do not edit this file.
"""


def slide_title(slide):
    texts = [sh.text_frame.text.strip() for sh in slide.shapes
             if sh.has_text_frame and sh.text_frame.text.strip()]
    for t in texts:
        if t.isupper() and len(t) < 60:
            continue
        return " ".join(t.split())
    return ""


def main(deck_path, out_path):
    prs = Presentation(deck_path)
    label = "CFO cut" if "-cfo" in deck_path else "default cut"
    out = [INTRO.format(label=label, deck=deck_path)]
    for n, slide in enumerate(prs.slides, 1):
        notes = slide.notes_slide.notes_text_frame.text.strip()
        out.append("\n## Slide %d — %s\n\n%s\n" % (n, slide_title(slide), notes))
    with open(out_path, "w") as fh:
        fh.write("\n".join(out))
    print("wrote %s (%d slides)" % (out_path, len(prs.slides._sldIdLst)))


if __name__ == "__main__":
    main(sys.argv[1], sys.argv[2])
